services:
  - type: static
    name: kenfuse-admin
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://kenfuse-main.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
